apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: uts9zrm4c-nodejs
  janus-idp.io/tekton: uts9zrm4c-nodejs
  backstage.io/kubernetes-id: uts9zrm4c-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: uts9zrm4c-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
